AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A simple AWS Lambda application that handles transactions.

Globals:
  Function:
    Timeout: 120 # Time in seconds until the function times out.

Resources:
  AuthorizationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dev.codescreen.handler.CreateAuthorizationTransactionHandler::handleRequest
      Runtime: java11
      CodeUri: ./target/TransactionServiceLambda-1.0.jar
      MemorySize: 1024
      Environment:
        Variables:
          LOCAL_MYSQL_HOST: "host.docker.internal"
          LOCAL_MYSQL_USERNAME: "Your-local-db-user-name"
          LOCAL_MYSQL_PASSWORD: "Your-local-db-password"
          LOCAL_MYSQL_DATABASE: "Your-local-db-dabase-name"
          RUN_ENVIRONMENT: "local"
      Events:
        LoadApi:
          Type: Api
          Properties:
            Path: /authorization/{messageId}
            Method: put

  LoadFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dev.codescreen.handler.CreateLoadTransactionHandler::handleRequest
      Runtime: java11
      CodeUri: ./target/TransactionServiceLambda-1.0.jar
      MemorySize: 1024
      Environment:
        Variables:
          LOCAL_MYSQL_HOST: "host.docker.internal"
          LOCAL_MYSQL_USERNAME: "Your-local-db-user-name"
          LOCAL_MYSQL_PASSWORD: "Your-local-db-password"
          LOCAL_MYSQL_DATABASE: "Your-local-db-dabase-name"
          RUN_ENVIRONMENT: "local"
      Events:
        AuthorizationApi:
          Type: Api
          Properties:
            Path: /load/{messageId}
            Method: put

  PingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./target/TransactionServiceLambda-1.0.jar
      Handler: dev.codescreen.handler.GetPingHandler::handleRequest
      Runtime: java11
      MemorySize: 512
      Timeout: 30
      Events:
        PingApi:
          Type: Api
          Properties:
            Path: /ping
            Method: get
